Nationality.create(id: '4', name: 'Afgana', country: 'Afganistán', iso2: 'AF')
Nationality.create(id: '248', name: 'Ålandesa', country: 'Islas Åland', iso2: 'AX')
Nationality.create(id: '8', name: 'Albanesa', country: 'Albania', iso2: 'AL')
Nationality.create(id: '276', name: 'Alemana', country: 'Alemania', iso2: 'DE')
Nationality.create(id: '20', name: 'Andorrana', country: 'Andorra', iso2: 'AD')
Nationality.create(id: '24', name: 'Angoleña', country: 'Angola', iso2: 'AO')
Nationality.create(id: '660', name: 'Anguilense', country: 'Anguilla', iso2: 'AI')
Nationality.create(id: '10', name: 'Antártica', country: 'Antártida', iso2: 'AQ')
Nationality.create(id: '28', name: 'Antiguana', country: 'Antigua y Barbuda', iso2: 'AG')
Nationality.create(id: '530', name: 'Antillana', country: 'Antillas Neerlandesas', iso2: 'AN')
Nationality.create(id: '682', name: 'Arabe', country: 'Arabia Saudí', iso2: 'SA')
Nationality.create(id: '12', name: 'Argelina', country: 'Argelia', iso2: 'DZ')
Nationality.create(id: '32', name: 'Argentina', country: 'Argentina', iso2: 'AR')
Nationality.create(id: '51', name: 'Armenia', country: 'Armenia', iso2: 'AM')
Nationality.create(id: '533', name: 'Arubeño', country: 'Aruba', iso2: 'AW')
Nationality.create(id: '36', name: 'Australiana', country: 'Australia', iso2: 'AU')
Nationality.create(id: '40', name: 'Austriaca', country: 'Austria', iso2: 'AT')
Nationality.create(id: '31', name: 'Azerbaiyana', country: 'Azerbaiyán', iso2: 'AZ')
Nationality.create(id: '44', name: 'Bahamesa', country: 'Bahamas', iso2: 'BS')
Nationality.create(id: '48', name: 'Bahreiní', country: 'Bahréin', iso2: 'BH')
Nationality.create(id: '50', name: 'Bangladesha', country: 'Bangladesh', iso2: 'BD')
Nationality.create(id: '52', name: 'Barbadesa', country: 'Barbados', iso2: 'BB')
Nationality.create(id: '112', name: 'Bielorrusa', country: 'Belarús', iso2: 'BY')
Nationality.create(id: '56', name: 'Belga', country: 'Bélgica', iso2: 'BE')
Nationality.create(id: '84', name: 'Beliceña', country: 'Belice', iso2: 'BZ')
Nationality.create(id: '204', name: 'Beninesa', country: 'Benin', iso2: 'BJ')
Nationality.create(id: '60', name: 'Bermudesa', country: 'Bermudas', iso2: 'BM')
Nationality.create(id: '64', name: 'Bhutanesa', country: 'Bhután', iso2: 'BT')
Nationality.create(id: '68', name: 'Boliviana', country: 'Bolivia', iso2: 'BO')
Nationality.create(id: '70', name: 'Bosnia', country: 'Bosnia y Herzegovina', iso2: 'BA')
Nationality.create(id: '72', name: 'Botsuana', country: 'Botsuana', iso2: 'BW')
Nationality.create(id: '74', name: 'Bouvetana', country: 'Isla Bouvet', iso2: 'BV')
Nationality.create(id: '76', name: 'Brasileña', country: 'Brasil', iso2: 'BR')
Nationality.create(id: '96', name: 'Bruneana', country: 'Brunéi', iso2: 'BN')
Nationality.create(id: '100', name: 'Búlgara', country: 'Bulgaria', iso2: 'BG')
Nationality.create(id: '854', name: 'Burkinesa', country: 'Burkina Faso', iso2: 'BF')
Nationality.create(id: '108', name: 'Burundiana', country: 'Burundi', iso2: 'BI')
Nationality.create(id: '132', name: 'Caboverdiana', country: 'Cabo Verde', iso2: 'CV')
Nationality.create(id: '136', name: 'Caimanesa', country: 'Islas Caimán', iso2: 'KY')
Nationality.create(id: '116', name: 'Camboyana', country: 'Camboya', iso2: 'KH')
Nationality.create(id: '120', name: 'Camerunesa', country: 'Camerún', iso2: 'CM')
Nationality.create(id: '124', name: 'Canadiense', country: 'Canadá', iso2: 'CA')
Nationality.create(id: '140', name: 'Centroafricana', country: 'República Centroafricana', iso2: 'CF')
Nationality.create(id: '148', name: 'Chadeña', country: 'Chad', iso2: 'TD')
Nationality.create(id: '203', name: 'Checa', country: 'Chequia', iso2: 'CZ')
Nationality.create(id: '152', name: 'Chilena', country: 'Chile', iso2: 'CL')
Nationality.create(id: '156', name: 'China', country: 'China', iso2: 'CN')
Nationality.create(id: '196', name: 'Chipriota', country: 'Chipre', iso2: 'CY')
Nationality.create(id: '162', name: 'De la Isla de Navidad', country: 'Isla Christmas', iso2: 'CX')
Nationality.create(id: '275', name: 'Palestino', country: 'Cisjordania', iso2: 'PS')
Nationality.create(id: '336', name: 'Vaticana', country: 'Ciudad del Vaticano', iso2: 'VA')
Nationality.create(id: '166', name: 'De la Isla de Cocos', country: 'Islas Cocos', iso2: 'CC')
Nationality.create(id: '170', name: 'Colombiana', country: 'Colombia', iso2: 'CO')
Nationality.create(id: '174', name: 'Comorana', country: 'Comoras', iso2: 'KM')
Nationality.create(id: '180', name: 'Congolesa', country: 'República Democrática del Congo', iso2: 'CD')
Nationality.create(id: '178', name: 'Congolesa', country: 'Congo', iso2: 'CG')
Nationality.create(id: '184', name: 'De la Isla de Cook', country: 'Islas Cook', iso2: 'CK')
Nationality.create(id: '408', name: 'Norcoreana', country: 'Corea del Norte', iso2: 'KP')
Nationality.create(id: '410', name: 'Surcoreana', country: 'Corea del Sur', iso2: 'KR')
Nationality.create(id: '384', name: 'Marfilesa', country: 'Costa de Marfil', iso2: 'CI')
Nationality.create(id: '188', name: 'Costarricense', country: 'Costa Rica', iso2: 'CR')
Nationality.create(id: '191', name: 'Croata', country: 'Croacia', iso2: 'HR')
Nationality.create(id: '192', name: 'Cubana', country: 'Cuba', iso2: 'CU')
Nationality.create(id: '208', name: 'Danesa', country: 'Dinamarca', iso2: 'DK')
Nationality.create(id: '212', name: 'Dominiquesa', country: 'Dominica', iso2: 'DM')
Nationality.create(id: '214', name: 'Dominicana', country: 'República Dominicana', iso2: 'DO')
Nationality.create(id: '218', name: 'Ecuatoriana', country: 'Ecuador', iso2: 'EC')
Nationality.create(id: '818', name: 'Egipcia', country: 'Egipto', iso2: 'EG')
Nationality.create(id: '222', name: 'Salvadoreña', country: 'El Salvador', iso2: 'SV')
Nationality.create(id: '784', name: 'Emiratounidense', country: 'Emiratos Árabes Unidos', iso2: 'AE')
Nationality.create(id: '232', name: 'Eritrea', country: 'Eritrea', iso2: 'ER')
Nationality.create(id: '703', name: 'Eslovaka', country: 'Eslovaquia', iso2: 'SK')
Nationality.create(id: '705', name: 'Eslovena', country: 'Eslovenia', iso2: 'SI')
Nationality.create(id: '724', name: 'Español', country: 'España', iso2: 'ES')
Nationality.create(id: '581', name: 'De las Islas Ultramarinas de Estados Unidos', country: 'Islas Ultramarinas de Estados Unidos', iso2: 'UM')
Nationality.create(id: '840', name: 'Estadounidense', country: 'Estados Unidos de América', iso2: 'US')
Nationality.create(id: '233', name: 'Estona', country: 'Estonia', iso2: 'EE')
Nationality.create(id: '231', name: 'Etíope', country: 'Etiopía', iso2: 'ET')
Nationality.create(id: '234', name: 'Feroésa', country: 'Islas Feroe', iso2: 'FO')
Nationality.create(id: '608', name: 'Filipina', country: 'Filipinas', iso2: 'PH')
Nationality.create(id: '246', name: 'Finesa', country: 'Finlandia', iso2: 'FI')
Nationality.create(id: '242', name: 'Fiyiana', country: 'Fiyi', iso2: 'FJ')
Nationality.create(id: '250', name: 'Francesa', country: 'Francia', iso2: 'FR')
Nationality.create(id: '266', name: 'Gabonesa', country: 'Gabón', iso2: 'GA')
Nationality.create(id: '270', name: 'Gabiana', country: 'Gambia', iso2: 'GM')
Nationality.create(id: '268', name: 'Georgiana', country: 'Georgia', iso2: 'GE')
Nationality.create(id: '239', name: 'Surgeorgiana', country: 'Georgia del Sur', iso2: 'GS')
Nationality.create(id: '288', name: 'Ghanesa', country: 'Ghana', iso2: 'GH')
Nationality.create(id: '292', name: 'Gibraltareño', country: 'Gibraltar', iso2: 'GI')
Nationality.create(id: '308', name: 'Granadeña', country: 'Granada', iso2: 'GD')
Nationality.create(id: '300', name: 'Griega', country: 'Grecia', iso2: 'GR')
Nationality.create(id: '304', name: 'Groenlandesa', country: 'Groenlandia', iso2: 'GL')
Nationality.create(id: '312', name: 'Guadalupeño', country: 'Guadalupe', iso2: 'GP')
Nationality.create(id: '316', name: 'Guameño', country: 'Guam', iso2: 'GU')
Nationality.create(id: '320', name: 'Guatemalteca', country: 'Guatemala', iso2: 'GT')
Nationality.create(id: '254', name: 'Guayanesa', country: 'Guayana Francesa', iso2: 'GF')
Nationality.create(id: '324', name: 'Guineana', country: 'Guinea', iso2: 'GN')
Nationality.create(id: '226', name: 'Ecuatoguineana', country: 'Guinea Ecuatorial', iso2: 'GQ')
Nationality.create(id: '624', name: 'Guineana', country: 'Guinea-Bissau', iso2: 'GW')
Nationality.create(id: '328', name: 'Guyanesa', country: 'Guyana', iso2: 'GY')
Nationality.create(id: '332', name: 'Haitiana', country: 'Haití', iso2: 'HT')
Nationality.create(id: '334', name: 'De las Islas Heard y McDonald', country: 'Islas Heard y McDonald', iso2: 'HM')
Nationality.create(id: '340', name: 'Hondureña', country: 'Honduras', iso2: 'HN')
Nationality.create(id: '344', name: 'Hongkonesa', country: 'Hong Kong', iso2: 'HK')
Nationality.create(id: '348', name: 'Húngara', country: 'Hungría', iso2: 'HU')
Nationality.create(id: '356', name: 'India', country: 'India', iso2: 'IN')
Nationality.create(id: '360', name: 'Indonesa', country: 'Indonesia', iso2: 'ID')
Nationality.create(id: '364', name: 'Iraní', country: 'Irán', iso2: 'IR')
Nationality.create(id: '368', name: 'Iraquí', country: 'Iraq', iso2: 'IQ')
Nationality.create(id: '372', name: 'Irlandesa', country: 'Irlanda', iso2: 'IE')
Nationality.create(id: '352', name: 'Islandesa', country: 'Islandia', iso2: 'IS')
Nationality.create(id: '376', name: 'Israelí', country: 'Israel', iso2: 'IL')
Nationality.create(id: '380', name: 'Italiana', country: 'Italia', iso2: 'IT')
Nationality.create(id: '388', name: 'Jamaiquina', country: 'Jamaica', iso2: 'JM')
Nationality.create(id: '392', name: 'Japonesa', country: 'Japón', iso2: 'JP')
Nationality.create(id: '400', name: 'Jordana', country: 'Jordania', iso2: 'JO')
Nationality.create(id: '398', name: 'Kazaka', country: 'Kazajstán', iso2: 'KZ')
Nationality.create(id: '404', name: 'Keniata', country: 'Kenia', iso2: 'KE')
Nationality.create(id: '417', name: 'Kirguís', country: 'Kirguistán', iso2: 'KG')
Nationality.create(id: '296', name: 'Kiribatí', country: 'Kiribati', iso2: 'KI')
Nationality.create(id: '414', name: 'Kuwaití', country: 'Kuwait', iso2: 'KW')
Nationality.create(id: '418', name: 'Laosiana', country: 'Laos', iso2: 'LA')
Nationality.create(id: '426', name: 'Lesothensa', country: 'Lesotho', iso2: 'LS')
Nationality.create(id: '428', name: 'Letón', country: 'Letonia', iso2: 'LV')
Nationality.create(id: '422', name: 'Libanesa', country: 'Líbano', iso2: 'LB')
Nationality.create(id: '430', name: 'Liberiana', country: 'Liberia', iso2: 'LR')
Nationality.create(id: '434', name: 'Libeña', country: 'Libia', iso2: 'LY')
Nationality.create(id: '438', name: 'Liechtenstein', country: 'Liechtenstein', iso2: 'LI')
Nationality.create(id: '440', name: 'Lituana', country: 'Lituania', iso2: 'LT')
Nationality.create(id: '442', name: 'Luxemburgues', country: 'Luxemburgo', iso2: 'LU')
Nationality.create(id: '446', name: 'Macaense', country: 'Macao', iso2: 'MO')
Nationality.create(id: '807', name: 'Macedonia', country: 'ARY Macedonia', iso2: 'MK')
Nationality.create(id: '450', name: 'Malgache', country: 'Madagascar', iso2: 'MG')
Nationality.create(id: '458', name: 'Malasia', country: 'Malasia', iso2: 'MY')
Nationality.create(id: '454', name: 'Malawi', country: 'Malawi', iso2: 'MW')
Nationality.create(id: '462', name: 'Maldivas', country: 'Maldivas', iso2: 'MV')
Nationality.create(id: '466', name: 'Maliense', country: 'Malí', iso2: 'ML')
Nationality.create(id: '470', name: 'Maltesa', country: 'Malta', iso2: 'MT')
Nationality.create(id: '238', name: 'Malvinense', country: 'Islas Malvinas', iso2: 'FK')
Nationality.create(id: '580', name: 'De las Islas Marianas del Norte', country: 'Islas Marianas del Norte', iso2: 'MP')
Nationality.create(id: '504', name: 'Marroquí', country: 'Marruecos', iso2: 'MA')
Nationality.create(id: '584', name: 'Marshalesa', country: 'Islas Marshall', iso2: 'MH')
Nationality.create(id: '474', name: 'Martiniquesa', country: 'Martinica', iso2: 'MQ')
Nationality.create(id: '480', name: 'Mauricio', country: 'Mauricio', iso2: 'MU')
Nationality.create(id: '478', name: 'Mauritana', country: 'Mauritania', iso2: 'MR')
Nationality.create(id: '175', name: 'Mayotense', country: 'Mayotte', iso2: 'YT')
Nationality.create(id: '484', name: 'Mexicana', country: 'México', iso2: 'MX')
Nationality.create(id: '583', name: 'Micronesia', country: 'Micronesia', iso2: 'FM')
Nationality.create(id: '498', name: 'Moldava', country: 'Moldova', iso2: 'MD')
Nationality.create(id: '492', name: 'Monegasca', country: 'Mónaco', iso2: 'MC')
Nationality.create(id: '496', name: 'Mongol', country: 'Mongolia', iso2: 'MN')
Nationality.create(id: '500', name: 'Montserratense', country: 'Montserrat', iso2: 'MS')
Nationality.create(id: '508', name: 'Mozambiqueña', country: 'Mozambique', iso2: 'MZ')
Nationality.create(id: '104', name: 'Birmana', country: 'Myanmar', iso2: 'MM')
Nationality.create(id: '516', name: 'Namibia', country: 'Namibia', iso2: 'NA')
Nationality.create(id: '520', name: 'Nauru', country: 'Nauru', iso2: 'NR')
Nationality.create(id: '524', name: 'Nepalesa', country: 'Nepal', iso2: 'NP')
Nationality.create(id: '558', name: 'Nicaragüense', country: 'Nicaragua', iso2: 'NI')
Nationality.create(id: '562', name: 'Nigerina', country: 'Níger', iso2: 'NE')
Nationality.create(id: '566', name: 'Nigeriana', country: 'Nigeria', iso2: 'NG')
Nationality.create(id: '570', name: 'Niueña', country: 'Niue', iso2: 'NU')
Nationality.create(id: '574', name: 'De la Isla Norfolk', country: 'Isla Norfolk', iso2: 'NF')
Nationality.create(id: '578', name: 'Noruega', country: 'Noruega', iso2: 'NO')
Nationality.create(id: '540', name: 'Neocaledonia', country: 'Nueva Caledonia', iso2: 'NC')
Nationality.create(id: '554', name: 'Neozelandesa', country: 'Nueva Zelanda', iso2: 'NZ')
Nationality.create(id: '512', name: 'Omaní', country: 'Omán', iso2: 'OM')
Nationality.create(id: '528', name: 'Neerlandesa', country: 'Países Bajos', iso2: 'NL')
Nationality.create(id: '586', name: 'Pakistaní', country: 'Pakistán', iso2: 'PK')
Nationality.create(id: '585', name: 'Palauana', country: 'Palaos', iso2: 'PW')
Nationality.create(id: '591', name: 'Panameña', country: 'Panamá', iso2: 'PA')
Nationality.create(id: '598', name: 'Papú', country: 'Papúa Nueva Guinea', iso2: 'PG')
Nationality.create(id: '600', name: 'Paraguaya', country: 'Paraguay', iso2: 'PY')
Nationality.create(id: '604', name: 'Peruana', country: 'Perú', iso2: 'PE')
Nationality.create(id: '612', name: 'Pitcairnesa', country: 'Islas Pitcairn', iso2: 'PN')
Nationality.create(id: '258', name: 'Polinesia', country: 'Polinesia Francesa', iso2: 'PF')
Nationality.create(id: '616', name: 'Polaca', country: 'Polonia', iso2: 'PL')
Nationality.create(id: '620', name: 'Portuguesa', country: 'Portugal', iso2: 'PT')
Nationality.create(id: '630', name: 'Puertorriqueña', country: 'Puerto Rico', iso2: 'PR')
Nationality.create(id: '634', name: 'Qatarí', country: 'Qatar', iso2: 'QA')
Nationality.create(id: '826', name: 'Británica', country: 'Reino Unido', iso2: 'GB')
Nationality.create(id: '638', name: 'Reunionesa', country: 'Reunión', iso2: 'RE')
Nationality.create(id: '646', name: 'Ruanda', country: 'Ruanda', iso2: 'RW')
Nationality.create(id: '642', name: 'Rumana', country: 'Rumanía', iso2: 'RO')
Nationality.create(id: '643', name: 'Rusa', country: 'Rusia', iso2: 'RU')
Nationality.create(id: '732', name: 'Saharaui', country: 'Sáhara Occidental', iso2: 'EH')
Nationality.create(id: '90', name: 'Salomonense', country: 'Islas Salomón', iso2: 'SB')
Nationality.create(id: '882', name: 'Samoana', country: 'Samoa', iso2: 'WS')
Nationality.create(id: '16', name: 'Samoamericana', country: 'Samoa Americana', iso2: 'AS')
Nationality.create(id: '659', name: 'Sancristobaleña', country: 'San Cristóbal y Nieves', iso2: 'KN')
Nationality.create(id: '674', name: 'Sanmarinense', country: 'San Marino', iso2: 'SM')
Nationality.create(id: '666', name: 'De San Pedro y Miquelón', country: 'San Pedro y Miquelón', iso2: 'PM')
Nationality.create(id: '670', name: 'Sanvicentina', country: 'San Vicente y las Granadinas', iso2: 'VC')
Nationality.create(id: '654', name: 'Santahelena', country: 'Santa Helena', iso2: 'SH')
Nationality.create(id: '662', name: 'Santalucense', country: 'Santa Lucía', iso2: 'LC')
Nationality.create(id: '678', name: 'Santotomense', country: 'Santo Tomé y Príncipe', iso2: 'ST')
Nationality.create(id: '686', name: 'Senegalesa', country: 'Senegal', iso2: 'SN')
Nationality.create(id: '891', name: 'Serbomontenegrina', country: 'Serbia y Montenegro', iso2: 'CS')
Nationality.create(id: '690', name: 'Serbomontenegrina', country: 'Seychelles', iso2: 'SC')
Nationality.create(id: '694', name: 'Sierraleonesa', country: 'Sierra Leona', iso2: 'SL')
Nationality.create(id: '702', name: 'Singapur', country: 'Singapur', iso2: 'SG')
Nationality.create(id: '760', name: 'Siria', country: 'Siria', iso2: 'SY')
Nationality.create(id: '706', name: 'Somalia', country: 'Somalia', iso2: 'SO')
Nationality.create(id: '144', name: 'Ceilandesa', country: 'Sri Lanka', iso2: 'LK')
Nationality.create(id: '748', name: 'Suazilandesa', country: 'Suazilandia', iso2: 'SZ')
Nationality.create(id: '710', name: 'Sudafricana', country: 'Sudáfrica', iso2: 'ZA')
Nationality.create(id: '736', name: 'Sudanesa', country: 'Sudán', iso2: 'SD')
Nationality.create(id: '752', name: 'Sueca', country: 'Suecia', iso2: 'SE')
Nationality.create(id: '756', name: 'Suiza', country: 'Suiza', iso2: 'CH')
Nationality.create(id: '740', name: 'Surinamesa', country: 'Surinam', iso2: 'SR')
Nationality.create(id: '744', name: 'Svalbardesa', country: 'Svalbard', iso2: 'SJ')
Nationality.create(id: '764', name: 'Tailandesa', country: 'Tailandia', iso2: 'TH')
Nationality.create(id: '158', name: 'Taiwanesa', country: 'Taiwán', iso2: 'TW')
Nationality.create(id: '834', name: 'Tanzana', country: 'Tanzania', iso2: 'TZ')
Nationality.create(id: '762', name: 'Tayika', country: 'Tayikistán', iso2: 'TJ')
Nationality.create(id: '86', name: 'Del Territorio Británico del Océano Índico', country: 'Territorio Británico del Océano Índico', iso2: 'IO')
Nationality.create(id: '260', name: 'De los Territorios Australes Franceses', country: 'Territorios Australes Franceses', iso2: 'TF')
Nationality.create(id: '626', name: 'Timorense', country: 'Timor Oriental', iso2: 'TL')
Nationality.create(id: '768', name: 'Togo', country: 'Togo', iso2: 'TG')
Nationality.create(id: '772', name: 'Tokelauésa', country: 'Tokelau', iso2: 'TK')
Nationality.create(id: '776', name: 'Tonga', country: 'Tonga', iso2: 'TO')
Nationality.create(id: '780', name: 'Trinitense', country: 'Trinidad y Tobago', iso2: 'TT')
Nationality.create(id: '788', name: 'Tunecina', country: 'Túnez', iso2: 'TN')
Nationality.create(id: '796', name: 'De las Islas Turcas y Caicos', country: 'Islas Turcas y Caicos', iso2: 'TC')
Nationality.create(id: '795', name: 'Turcomana', country: 'Turkmenistán', iso2: 'TM')
Nationality.create(id: '792', name: 'Turca', country: 'Turquía', iso2: 'TR')
Nationality.create(id: '798', name: 'Tuvaluana', country: 'Tuvalu', iso2: 'TV')
Nationality.create(id: '804', name: 'Ucraniana', country: 'Ucrania', iso2: 'UA')
Nationality.create(id: '800', name: 'Ugandesa', country: 'Uganda', iso2: 'UG')
Nationality.create(id: '858', name: 'Uruguaya', country: 'Uruguay', iso2: 'UY')
Nationality.create(id: '860', name: 'Uzbeka', country: 'Uzbekistán', iso2: 'UZ')
Nationality.create(id: '548', name: 'Vanuatense', country: 'Vanuatu', iso2: 'VU')
Nationality.create(id: '862', name: 'Venezolana', country: 'Venezuela', iso2: 'VE')
Nationality.create(id: '704', name: 'Vietnamita', country: 'Vietnam', iso2: 'VN')
Nationality.create(id: '92', name: 'De las Islas Vírgenes Británicas', country: 'Islas Vírgenes Británicas', iso2: 'VG')
Nationality.create(id: '850', name: 'De las Islas Vírgenes de los Estados Unidos', country: 'Islas Vírgenes de los Estados Unidos', iso2: 'VI')
Nationality.create(id: '876', name: 'De las Islas Wallis y Futuna', country: 'Islas Wallis y Futuna', iso2: 'WF')
Nationality.create(id: '887', name: 'Yemení', country: 'Yemen', iso2: 'YE')
Nationality.create(id: '262', name: 'Yibutiense', country: 'Yibuti', iso2: 'DJ')
Nationality.create(id: '894', name: 'Zambiana', country: 'Zambia', iso2: 'ZM')
Nationality.create(id: '716', name: 'Zimbabuense', country: 'Zimbabue', iso2: 'ZW')
Nationality.create(id: '1001', name: 'Holandes', country: 'Holanda', iso2: 'HL')
